# Testing -  ***  Moved the env variable assignment as part of Jobs ***

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Master" branch
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

# Allows you to run this workflow manually from the Actions tab
#workflow_dispatch:
env:         
     # Replace with your Orchestrator Values 
  PROJECT_NAME: Test_Deployment_Process
  PROJECT_FOLDER: ${{ github.action_path }}
  ORCH_URL: https://cloud.uipath.com/hocine/Hocine
  ORCH_TENANT: "Hocine"
  ORCH_CLIENT_ID: "8DEv1AMNXczW3y4U15LL3jYf62jK93n5"
  ORCH_USER_KEY: "VXs5mjIF0WIHK-Z5bsakaJwi16cwsR3R12YoSaCrn7FfT"
  ORCH_ACC_NAME: hocine
  Package_Name: Test_Deployment_Process.1.0.1.nupkg

jobs:  
  print-details:
   # needs: Assing-Environment-Variables
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo  env.project_name